"""Custom Report service — saving, running and delivering user-built
reports.

Every run goes through report_builder.run_report(), which re-validates
the saved keys against the curated whitelist. Nothing here trusts the
stored definition to still be valid (a column could have been removed
since it was saved) or to be safe (a row could have been edited directly
in the database).
"""
import json

from app.extensions import db
from app.modules.system_admin.models import CustomReport
from app.core.reporting.report_builder import (
    DATA_SOURCES, run_report, to_xlsx, ReportBuilderError)


class CustomReportService:

    def list(self, include_inactive: bool = False) -> list:
        query = CustomReport.query
        if not include_inactive:
            query = query.filter_by(is_active=True)
        return query.order_by(CustomReport.name.asc()).all()

    def get_by_id(self, report_id: int):
        return db.session.get(CustomReport, report_id)

    def create(self, *, name, data_source, fields, filters=None,
               sort_key=None, sort_dir="asc", description=None,
               row_limit=1000, default_recipients=None, user=None):
        self._validate(name, data_source, fields)
        report = CustomReport(
            name=name.strip(), description=(description or "").strip() or None,
            data_source=data_source,
            fields_json=json.dumps(list(fields)),
            filters_json=json.dumps(filters or []),
            sort_key=sort_key or None, sort_dir=sort_dir or "asc",
            row_limit=int(row_limit or 1000),
            default_recipients=(default_recipients or "").strip() or None,
            created_by=user.id if user else None)
        db.session.add(report)
        db.session.commit()
        return report

    def update(self, report_id, *, name, data_source, fields, filters=None,
               sort_key=None, sort_dir="asc", description=None,
               row_limit=1000, default_recipients=None, user=None):
        report = self.get_by_id(report_id)
        if report is None:
            raise ReportBuilderError("Report not found.")
        self._validate(name, data_source, fields)
        report.name = name.strip()
        report.description = (description or "").strip() or None
        report.data_source = data_source
        report.fields_json = json.dumps(list(fields))
        report.filters_json = json.dumps(filters or [])
        report.sort_key = sort_key or None
        report.sort_dir = sort_dir or "asc"
        report.row_limit = int(row_limit or 1000)
        report.default_recipients = (default_recipients or "").strip() or None
        report.updated_by = user.id if user else None
        db.session.commit()
        return report

    def deactivate(self, report_id):
        report = self.get_by_id(report_id)
        if report:
            report.is_active = False
            db.session.commit()

    def _validate(self, name, data_source, fields):
        if not (name or "").strip():
            raise ReportBuilderError("Give the report a name.")
        if data_source not in DATA_SOURCES:
            raise ReportBuilderError(f"Unknown data source '{data_source}'.")
        source = DATA_SOURCES[data_source]
        valid = [f for f in (fields or []) if f in source.fields]
        if not valid:
            raise ReportBuilderError("Select at least one column.")

    def run(self, report, user=None) -> dict:
        """Execute a saved report. The permission check lives in
        run_report(), keyed off the data source, so a saved report can
        never expose data the person couldn't otherwise see."""
        return run_report(
            report.data_source, report.fields, filters=report.filters,
            sort_key=report.sort_key, sort_dir=report.sort_dir,
            limit=report.row_limit, user=user)

    def to_excel(self, report, user=None) -> tuple:
        result = self.run(report, user=user)
        data = to_xlsx(result, title=report.name)
        safe_name = "".join(
            ch for ch in report.name if ch.isalnum() or ch in " -_").strip()
        return f"{safe_name or 'Custom_Report'}.xlsx", data

    def email(self, report, recipients=None, user=None) -> dict:
        """Queue the report for delivery as an Excel attachment.

        Goes through the EmailOutbox rather than sending inline, for the
        same reason notification email does: the person clicking "Email"
        gets an immediate response instead of waiting on SMTP. The
        workbook is generated by the DRAIN at send time (see
        EmailOutboxService), not stored here -- that keeps potentially
        large spreadsheets out of the database, and means a report
        delivered on a schedule carries current data rather than a
        snapshot from whenever the schedule was set up.
        """
        addresses = [a.strip() for a in
                    (recipients or report.default_recipients or "").replace(
                        ";", ",").split(",") if a.strip()]
        if not addresses:
            raise ReportBuilderError(
                "No recipients given, and this report has no default "
                "recipients saved.")
        # Fail fast: if the definition can't run, say so now rather than
        # silently queueing mail that will fail later out of sight.
        self.run(report, user=user)

        from app.modules.system_admin.models import EmailOutbox
        for address in addresses:
            db.session.add(EmailOutbox(
                to_email=address,
                to_user_id=user.id if user else None,
                subject=f"[FMS] {report.name}",
                body_html=(
                    f"<p>Attached is the <strong>{report.name}</strong> "
                    f"report from the Fleet Management System.</p>"
                    f"<p>{report.description or ''}</p>"),
                event_code="CUSTOM_REPORT",
                reference_table="custom_reports",
                reference_id=report.id,
                status="PENDING"))
        db.session.commit()
        return {"queued": len(addresses), "recipients": addresses}
