"""add user.is_lockout_exempt

Revision ID: 0354058b0cf4
Revises: f425c85c573f
Create Date: 2026-08-06 12:30:06.614120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0354058b0cf4'
down_revision = 'f425c85c573f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lockout_exempt', sa.Boolean(),
                                      nullable=False,
                                      server_default=sa.false()))
    # Drop the server_default once existing rows are backfilled -- it
    # was only needed to satisfy the NOT NULL constraint during the
    # ALTER itself; new rows should rely on the model's own default.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_lockout_exempt', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_lockout_exempt')

    # ### end Alembic commands ###
