"""add vendor_contacts table for Vendor Other Contact feature

Revision ID: 0b2760c4693f
Revises: ec99571c95ef
Create Date: 2026-07-18 18:14:29.009745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2760c4693f'
down_revision = 'ec99571c95ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_contacts',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('tel_number', sa.String(length=50), nullable=True),
    sa.Column('cel_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_contacts_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_contacts_vendor_id'))

    op.drop_table('vendor_contacts')
    # ### end Alembic commands ###
