"""add fuel management

Revision ID: 0fe7865a9de2
Revises: edb6ff9c1193
Create Date: 2026-08-04 06:40:28.711070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7865a9de2'
down_revision = 'edb6ff9c1193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_cards',
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    with op.batch_alter_table('fuel_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_cards_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_cards_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('fuel_transactions',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('fuel_card_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('station', sa.String(length=120), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('litres', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_per_litre', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('odometer_reported', sa.Integer(), nullable=True),
    sa.Column('odometer_used', sa.Integer(), nullable=True),
    sa.Column('odometer_status', sa.String(length=15), nullable=False),
    sa.Column('odometer_note', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('km_per_litre', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_per_km', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('anomaly_flags', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['fuel_card_id'], ['fuel_cards.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'transaction_date', 'reference_number', name='uq_fuel_txn_vehicle_date_ref')
    )
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_transactions_document_number'), ['document_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_fuel_transactions_fuel_card_id'), ['fuel_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_transactions_odometer_status'), ['odometer_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_transactions_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_transactions_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_odometer_status'))
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_fuel_card_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_document_number'))

    op.drop_table('fuel_transactions')
    with op.batch_alter_table('fuel_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_cards_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_cards_driver_id'))

    op.drop_table('fuel_cards')
    # ### end Alembic commands ###
