"""Registration PMS - registration_templates, registration_checklist_items, registration_transaction_checklist_items tables

Revision ID: 144d3c4c0cb0
Revises: ad2b0158cb93
Create Date: 2026-07-17 06:08:58.106756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144d3c4c0cb0'
down_revision = 'ad2b0158cb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_templates',
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_brand_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_model_id', sa.Integer(), nullable=True),
    sa.Column('interval_years', sa.Integer(), nullable=False),
    sa.Column('next_generation_policy', sa.String(length=20), nullable=False),
    sa.Column('notify_before_days', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['vehicle_brands.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_templates_vehicle_brand_id'), ['vehicle_brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_templates_vehicle_model_id'), ['vehicle_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_templates_vehicle_type_id'), ['vehicle_type_id'], unique=False)

    op.create_table('registration_checklist_items',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=40), nullable=False),
    sa.Column('activity_description', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['registration_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_checklist_items_template_id'), ['template_id'], unique=False)

    op.create_table('registration_transaction_checklist_items',
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=40), nullable=False),
    sa.Column('activity_description', sa.String(length=255), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['vehicle_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_transaction_checklist_items')
    with op.batch_alter_table('registration_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_checklist_items_template_id'))

    op.drop_table('registration_checklist_items')
    with op.batch_alter_table('registration_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_templates_vehicle_type_id'))
        batch_op.drop_index(batch_op.f('ix_registration_templates_vehicle_model_id'))
        batch_op.drop_index(batch_op.f('ix_registration_templates_vehicle_brand_id'))

    op.drop_table('registration_templates')
    # ### end Alembic commands ###
