"""add disposal fields to maintenance_orders for retirement lifecycle stage

Revision ID: 1b340985efd3
Revises: 733c1e1ea050
Create Date: 2026-07-21 05:12:13.893281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b340985efd3'
down_revision = '733c1e1ea050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposal_value', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('disposal_recipient', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('disposal_reference_number', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_column('disposal_reference_number')
        batch_op.drop_column('disposal_recipient')
        batch_op.drop_column('disposal_value')

    # ### end Alembic commands ###
