"""Maintenance Invoice and Actual Expense Management - new maintenance_invoices and maintenance_invoice_lines tables

Revision ID: 1b84042b75ce
Revises: 608d7fa437b0
Create Date: 2026-07-17 04:48:30.197944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b84042b75ce'
down_revision = '608d7fa437b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_invoices',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('maintenance_order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('or_number', sa.String(length=60), nullable=True),
    sa.Column('po_number', sa.String(length=60), nullable=True),
    sa.Column('dr_number', sa.String(length=60), nullable=True),
    sa.Column('vat_type', sa.String(length=15), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('total_parts_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_labor_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_invoice_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['maintenance_order_id'], ['maintenance_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_invoices_document_number'), ['document_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_maintenance_invoices_maintenance_order_id'), ['maintenance_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_invoices_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('maintenance_invoice_lines',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=True),
    sa.Column('part_description', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expense_category', sa.String(length=20), nullable=False),
    sa.Column('charged_to', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['maintenance_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_invoice_lines_invoice_id'))

    op.drop_table('maintenance_invoice_lines')
    with op.batch_alter_table('maintenance_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_invoices_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_invoices_maintenance_order_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_invoices_document_number'))

    op.drop_table('maintenance_invoices')
    # ### end Alembic commands ###
