"""add cumulative_km to pm_schedules

Revision ID: 21a8acd0ebe1
Revises: 762464cd7a40
Create Date: 2026-07-22 13:47:37.926119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a8acd0ebe1'
down_revision = '762464cd7a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_km', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pm_schedules_cumulative_km'), ['cumulative_km'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_schedules_cumulative_km'))
        batch_op.drop_column('cumulative_km')

    # ### end Alembic commands ###
