"""add historical vehicle-history migration tracking

Revision ID: 2653e0749763
Revises: 0354058b0cf4
Create Date: 2026-08-07 12:32:41.059406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2653e0749763'
down_revision = '0354058b0cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_import_batches',
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('imported_by', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('maintenance_rows', sa.Integer(), nullable=False),
    sa.Column('registration_rows', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_historical', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('historical_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mo_historical_batch', 'historical_import_batches', ['historical_batch_id'], ['id'])
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.alter_column('is_historical', server_default=None)

    with op.batch_alter_table('vehicle_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_historical', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('historical_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vr_historical_batch', 'historical_import_batches', ['historical_batch_id'], ['id'])
    with op.batch_alter_table('vehicle_registrations', schema=None) as batch_op:
        batch_op.alter_column('is_historical', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vr_historical_batch', type_='foreignkey')
        batch_op.drop_column('historical_batch_id')
        batch_op.drop_column('is_historical')

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mo_historical_batch', type_='foreignkey')
        batch_op.drop_column('historical_batch_id')
        batch_op.drop_column('is_historical')

    op.drop_table('historical_import_batches')
    # ### end Alembic commands ###
