"""add odometer_confirmed

Revision ID: 3fdf2cde1ed4
Revises: 0fe7865a9de2
Create Date: 2026-08-04 06:43:25.024464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdf2cde1ed4'
down_revision = '0fe7865a9de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_confirmed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.drop_column('odometer_confirmed')

    # ### end Alembic commands ###
