"""add maintenance order parts and purchase request link

Revision ID: 4e2f3f80f518
Revises: 663c51b0921a
Create Date: 2026-08-13 04:14:30.865135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2f3f80f518'
down_revision = '663c51b0921a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_order_parts',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=True),
    sa.Column('part_description', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_unit_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['maintenance_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_order_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_order_parts_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mo_purchase_request', 'purchase_requests', ['purchase_request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mo_purchase_request', type_='foreignkey')
        batch_op.drop_column('purchase_request_id')

    with op.batch_alter_table('maintenance_order_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_order_parts_order_id'))

    op.drop_table('maintenance_order_parts')
    # ### end Alembic commands ###
