"""add last_known_registration_expiry to vehicles

Revision ID: 4eefb27ec697
Revises: c70e3e7add4d
Create Date: 2026-07-20 13:58:27.344461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eefb27ec697'
down_revision = 'c70e3e7add4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_known_registration_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('last_known_registration_expiry')

    # ### end Alembic commands ###
