"""add document_comments table for the generic discussion thread feature

Revision ID: 51dc865e4fa9
Revises: 4e9dd195ce1a
Create Date: 2026-07-15 08:46:12.702328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51dc865e4fa9'
down_revision = '4e9dd195ce1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_comments',
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comments_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comments_reference_table'), ['reference_table'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comments_reference_table'))
        batch_op.drop_index(batch_op.f('ix_document_comments_reference_id'))

    op.drop_table('document_comments')
    # ### end Alembic commands ###
