"""Employee/Vehicle Assignee Master - expanded Driver profile fields, EmergencyContact table, nullable license fields

Revision ID: 5f9509d3931b
Revises: 0b2760c4693f
Create Date: 2026-07-18 22:27:35.081732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9509d3931b'
down_revision = '0b2760c4693f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_emergency_contacts',
    sa.Column('person_record_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_record_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_emergency_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_emergency_contacts_person_record_id'), ['person_record_id'], unique=False)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=80), nullable=True))
        # server_default required: MySQL rejects a NOT NULL column added
        # to a table that already has rows unless a default backfills
        # them. Every existing driver record becomes assignee_type=
        # DRIVER, matching the Python-side default and preserving every
        # existing driver's behavior exactly (license fields stay
        # required for them, same as before this feature existed).
        batch_op.add_column(sa.Column('assignee_type', sa.String(length=20),
                                      nullable=False, server_default='DRIVER'))
        batch_op.add_column(sa.Column('section', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost_center', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('office_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('home_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('complete_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_person', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_contact_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.alter_column('license_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('license_expiry',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('license_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_drivers_person_id'), ['person_id'], unique=True)
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('assignee_type', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_person_id'))
        batch_op.alter_column('license_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('license_expiry',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('license_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_contact_no')
        batch_op.drop_column('business_name')
        batch_op.drop_column('emergency_contact_number')
        batch_op.drop_column('emergency_contact_person')
        batch_op.drop_column('complete_address')
        batch_op.drop_column('home_number')
        batch_op.drop_column('office_number')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('cost_center')
        batch_op.drop_column('position')
        batch_op.drop_column('section')
        batch_op.drop_column('assignee_type')
        batch_op.drop_column('nickname')
        batch_op.drop_column('suffix')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('person_emergency_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_emergency_contacts_person_record_id'))

    op.drop_table('person_emergency_contacts')
    # ### end Alembic commands ###
