"""add work_description_template and interval_hours to pm_schedules

Revision ID: 6501c1df2210
Revises: 1b340985efd3
Create Date: 2026-07-21 12:55:14.963590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6501c1df2210'
down_revision = '1b340985efd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('work_description_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.drop_column('work_description_template')
        batch_op.drop_column('interval_hours')

    # ### end Alembic commands ###
