"""add department cost center

Revision ID: 663c51b0921a
Revises: 8218c6ac251a
Create Date: 2026-08-12 15:30:13.558129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663c51b0921a'
down_revision = '8218c6ac251a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_cost_center'), ['cost_center'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_cost_center'))
        batch_op.drop_column('cost_center')

    # ### end Alembic commands ###
