"""vendor many-to-many branch/business_unit associations

Revision ID: 69830f508e7b
Revises: ae033f6b8f34
Create Date: 2026-07-12 15:14:56.207974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69830f508e7b'
down_revision = 'ae033f6b8f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_branches',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'branch_id')
    )
    op.create_table('vendor_business_units',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('business_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'business_unit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_business_units')
    op.drop_table('vendor_branches')
    # ### end Alembic commands ###
