"""add assignment_classification to maintenance_orders for Vehicle Assignment Memo

Revision ID: 762464cd7a40
Revises: 6501c1df2210
Create Date: 2026-07-21 14:25:16.517404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762464cd7a40'
down_revision = '6501c1df2210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_classification', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_column('assignment_classification')

    # ### end Alembic commands ###
