"""F1+F2: user org scope, approval instance org context, approval task inbox

Revision ID: 790396a1bd15
Revises: 4eaed022ca9a
Create Date: 2026-07-12 06:51:19.378706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790396a1bd15'
down_revision = '4eaed022ca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_org_scopes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_tasks',
    sa.Column('approval_instance_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('assigned_role_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('approval_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('business_unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_approval_instances_business_unit_id',
                                    'business_units', ['business_unit_id'], ['id'])
        batch_op.create_foreign_key('fk_approval_instances_branch_id',
                                    'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_instances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_approval_instances_branch_id', type_='foreignkey')
        batch_op.drop_constraint('fk_approval_instances_business_unit_id', type_='foreignkey')
        batch_op.drop_column('business_unit_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tasks_status'))

    op.drop_table('approval_tasks')
    op.drop_table('user_org_scopes')
    # ### end Alembic commands ###
