"""PM template revision: make/model matching, vehicle template assignment, per-template alerts

Revision ID: 7bcd894c76b6
Revises: 31a79bfc2a7d
Create Date: 2026-07-11 16:17:25.379324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcd894c76b6'
down_revision = '31a79bfc2a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_make', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('vehicle_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('notify_before_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notify_before_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escalate_if_overdue', sa.Boolean(), nullable=False))

    with op.batch_alter_table('pm_scope_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_schedule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pm_scope_templates_pm_schedule_id',
                                    'pm_schedules', ['pm_schedule_id'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pm_schedule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vehicles_pm_schedule_id',
                                    'pm_schedules', ['pm_schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicles_pm_schedule_id', type_='foreignkey')
        batch_op.drop_column('pm_schedule_id')

    with op.batch_alter_table('pm_scope_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pm_scope_templates_pm_schedule_id', type_='foreignkey')
        batch_op.drop_column('pm_schedule_id')

    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.drop_column('escalate_if_overdue')
        batch_op.drop_column('notify_before_days')
        batch_op.drop_column('notify_before_km')
        batch_op.drop_column('vehicle_model')
        batch_op.drop_column('vehicle_make')

    # ### end Alembic commands ###
