"""phase 1b: document types, numbering, approval paths/matrix/instances

Revision ID: 7db21ed5ebec
Revises: 187f0fe8acd6
Create Date: 2026-07-10 09:36:30.507709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db21ed5ebec'
down_revision = '187f0fe8acd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_paths',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('auto_numbering', sa.Boolean(), nullable=False),
    sa.Column('printable', sa.Boolean(), nullable=False),
    sa.Column('mobile_available', sa.Boolean(), nullable=False),
    sa.Column('attachment_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_code'), ['code'], unique=True)

    op.create_table('approval_instances',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('approval_path_id', sa.Integer(), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_path_id'], ['approval_paths.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_instances_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_instances_reference_table'), ['reference_table'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_instances_status'), ['status'], unique=False)

    op.create_table('approval_levels',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('approver_type', sa.String(length=10), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['approval_paths.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'level_number', name='uq_path_level')
    )
    op.create_table('approval_matrices',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('approval_path_id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_path_id'], ['approval_paths.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbering_schemes',
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=False),
    sa.Column('include_year', sa.Boolean(), nullable=False),
    sa.Column('include_month', sa.Boolean(), nullable=False),
    sa.Column('digit_count', sa.Integer(), nullable=False),
    sa.Column('separator', sa.String(length=3), nullable=False),
    sa.Column('reset_policy', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type_id')
    )
    op.create_table('approval_actions',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('acted_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['approval_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbering_counters',
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['numbering_schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'year', 'month', name='uq_counter_scope')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numbering_counters')
    op.drop_table('approval_actions')
    op.drop_table('numbering_schemes')
    op.drop_table('approval_matrices')
    op.drop_table('approval_levels')
    with op.batch_alter_table('approval_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_instances_status'))
        batch_op.drop_index(batch_op.f('ix_approval_instances_reference_table'))
        batch_op.drop_index(batch_op.f('ix_approval_instances_reference_id'))

    op.drop_table('approval_instances')
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_types_code'))

    op.drop_table('document_types')
    op.drop_table('approval_paths')
    # ### end Alembic commands ###
