"""add driver photo attachment

Revision ID: 8218c6ac251a
Revises: 2653e0749763
Create Date: 2026-08-10 09:31:05.954428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8218c6ac251a'
down_revision = '2653e0749763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_attachment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_drivers_photo_attachment', 'attachments', ['photo_attachment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drivers_photo_attachment', type_='foreignkey')
        batch_op.drop_column('photo_attachment_id')

    # ### end Alembic commands ###
