"""phase 3b: PM scheduling, maintenance orders, tire/battery transactions

Revision ID: 8ef6625ec10a
Revises: ea9833b26262
Create Date: 2026-07-11 00:51:10.583782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef6625ec10a'
down_revision = 'ea9833b26262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_schedules',
    sa.Column('vehicle_type_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type_id', sa.Integer(), nullable=False),
    sa.Column('trigger_mode', sa.String(length=10), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['maintenance_types.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_scope_templates',
    sa.Column('maintenance_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['maintenance_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_scope_items',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=40), nullable=False),
    sa.Column('activity_description', sa.String(length=255), nullable=False),
    sa.Column('standard_labor_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('required_parts', sa.Text(), nullable=True),
    sa.Column('vendor_recommendation', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['pm_scope_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_orders',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=12), nullable=False),
    sa.Column('pm_schedule_id', sa.Integer(), nullable=True),
    sa.Column('scope_template_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('odometer_at_service', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('assigned_mechanic', sa.String(length=120), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['maintenance_types.id'], ),
    sa.ForeignKeyConstraint(['pm_schedule_id'], ['pm_schedules.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scope_template_id'], ['pm_scope_templates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_orders_document_number'), ['document_number'], unique=True)

    op.create_table('battery_transactions',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battery_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battery_transactions_document_number'), ['document_number'], unique=True)

    op.create_table('maintenance_checklist_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=40), nullable=False),
    sa.Column('activity_description', sa.String(length=255), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['maintenance_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tire_transactions',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('tire_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('odometer_at_service', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tire_id'], ['tires.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tire_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tire_transactions_document_number'), ['document_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tire_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tire_transactions_document_number'))

    op.drop_table('tire_transactions')
    op.drop_table('maintenance_checklist_items')
    with op.batch_alter_table('battery_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battery_transactions_document_number'))

    op.drop_table('battery_transactions')
    with op.batch_alter_table('maintenance_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_orders_document_number'))

    op.drop_table('maintenance_orders')
    op.drop_table('pm_scope_items')
    op.drop_table('pm_scope_templates')
    op.drop_table('pm_schedules')
    # ### end Alembic commands ###
