"""add file_data to attachments for shared DB storage

Revision ID: 9230c5844ae6
Revises: 4eefb27ec697
Create Date: 2026-07-20 14:25:49.978758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9230c5844ae6'
down_revision = '4eefb27ec697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
