"""add indexes to PM module FK columns for list-page performance

Revision ID: 9251a86c27dd
Revises: b094aeb877a7
Create Date: 2026-07-15 17:43:15.879637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9251a86c27dd'
down_revision = 'b094aeb877a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_schedules_maintenance_type_id'), ['maintenance_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_schedules_vehicle_brand_id'), ['vehicle_brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_schedules_vehicle_model_id'), ['vehicle_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_schedules_vehicle_type_id'), ['vehicle_type_id'], unique=False)

    with op.batch_alter_table('pm_scope_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_scope_items_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('pm_scope_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_scope_templates_maintenance_type_id'), ['maintenance_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_scope_templates_pm_schedule_id'), ['pm_schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_scope_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_scope_templates_pm_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_pm_scope_templates_maintenance_type_id'))

    with op.batch_alter_table('pm_scope_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_scope_items_template_id'))

    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_schedules_vehicle_type_id'))
        batch_op.drop_index(batch_op.f('ix_pm_schedules_vehicle_model_id'))
        batch_op.drop_index(batch_op.f('ix_pm_schedules_vehicle_brand_id'))
        batch_op.drop_index(batch_op.f('ix_pm_schedules_maintenance_type_id'))

    # ### end Alembic commands ###
