"""add odometer_at_registration to vehicle_registrations

Revision ID: 9f84bf5ae91a
Revises: 51dc865e4fa9
Create Date: 2026-07-15 09:07:27.916782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f84bf5ae91a'
down_revision = '51dc865e4fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_at_registration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_registrations', schema=None) as batch_op:
        batch_op.drop_column('odometer_at_registration')

    # ### end Alembic commands ###
