"""add custom_reports table

Revision ID: a1f9387a2071
Revises: a9dc8acf3d4a
Create Date: 2026-07-23 15:11:41.721678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f9387a2071'
down_revision = 'a9dc8acf3d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_reports',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('data_source', sa.String(length=60), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('sort_key', sa.String(length=60), nullable=True),
    sa.Column('sort_dir', sa.String(length=4), nullable=False),
    sa.Column('row_limit', sa.Integer(), nullable=False),
    sa.Column('default_recipients', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_reports')
    # ### end Alembic commands ###
