"""add email_outbox queue table

Revision ID: a9dc8acf3d4a
Revises: 21a8acd0ebe1
Create Date: 2026-07-23 08:29:57.584369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dc8acf3d4a'
down_revision = '21a8acd0ebe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('event_code', sa.String(length=60), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_outbox_event_code'), ['event_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_to_email'), ['to_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_outbox_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_event_code'))

    op.drop_table('email_outbox')
    # ### end Alembic commands ###
