"""add job_title to drivers for the Dynamic PM Work Order Report Assignee Position field

Revision ID: ad2b0158cb93
Revises: 1b84042b75ce
Create Date: 2026-07-17 05:08:35.434863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2b0158cb93'
down_revision = '1b84042b75ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
