"""add maintenance_class to mo_transaction_types

Revision ID: b136317c78dc
Revises: a1f9387a2071
Create Date: 2026-08-03 05:18:12.729643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b136317c78dc'
down_revision = 'a1f9387a2071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_transaction_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_class', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mo_transaction_types', schema=None) as batch_op:
        batch_op.drop_column('maintenance_class')

    # ### end Alembic commands ###
