"""PMS-2: profile_code shareable across sibling packages, sequence_position for display order

Revision ID: b1ec51b8847e
Revises: 19f17503b776
Create Date: 2026-07-13 21:52:07.635916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ec51b8847e'
down_revision = '19f17503b776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_position', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_pm_schedules_profile_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_pm_schedules_profile_code'), ['profile_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_schedules_profile_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_pm_schedules_profile_code'), ['profile_code'])
        batch_op.drop_column('sequence_position')

    # ### end Alembic commands ###
