"""add scheduled_reports table

Revision ID: c70e3e7add4d
Revises: ec220707401d
Create Date: 2026-07-19 22:17:42.405333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70e3e7add4d'
down_revision = 'ec220707401d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_reports',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('report_code', sa.String(length=60), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_reports')
    # ### end Alembic commands ###
