"""phase 1c: system admin, lookups, company, email templates, notifications

Revision ID: de01eb447e14
Revises: 7db21ed5ebec
Create Date: 2026-07-10 12:44:49.469189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de01eb447e14'
down_revision = '7db21ed5ebec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_configs',
    sa.Column('schedule', sa.String(length=10), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('destination_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profiles',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_widgets',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('default_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('email_templates',
    sa.Column('event_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_event_code'), ['event_code'], unique=True)

    op.create_table('lookups',
    sa.Column('lookup_type', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_type', 'code', name='uq_lookup_type_code')
    )
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookups_lookup_type'), ['lookup_type'], unique=False)

    op.create_table('report_configs',
    sa.Column('report_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('template_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_code')
    )
    op.create_table('system_parameters',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_parameters_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_parameters_group_name'), ['group_name'], unique=False)

    op.create_table('in_app_notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_code', sa.String(length=80), nullable=True),
    sa.Column('reference_table', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_in_app_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_in_app_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('notification_rules',
    sa.Column('event_code', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_rules_event_code'), ['event_code'], unique=False)

    op.create_table('user_dashboard_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_code', sa.String(length=80), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'widget_code', name='uq_user_widget')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_dashboard_configs')
    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_rules_event_code'))

    op.drop_table('notification_rules')
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_in_app_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_in_app_notifications_is_read'))

    op.drop_table('in_app_notifications')
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_parameters_group_name'))
        batch_op.drop_index(batch_op.f('ix_system_parameters_code'))

    op.drop_table('system_parameters')
    op.drop_table('report_configs')
    with op.batch_alter_table('lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookups_lookup_type'))

    op.drop_table('lookups')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_event_code'))

    op.drop_table('email_templates')
    op.drop_table('dashboard_widgets')
    op.drop_table('company_profiles')
    op.drop_table('backup_configs')
    # ### end Alembic commands ###
