"""phase 3a: trip ticket, authority to drive, vehicle movement

Revision ID: ea9833b26262
Revises: 3b9c795f2abe
Create Date: 2026-07-10 23:31:30.203986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9833b26262'
down_revision = '3b9c795f2abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_to_drives',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authority_to_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authority_to_drives_document_number'), ['document_number'], unique=True)

    op.create_table('trip_tickets',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('driver_name_manual', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('return_datetime', sa.DateTime(), nullable=True),
    sa.Column('odometer_out', sa.Integer(), nullable=True),
    sa.Column('odometer_in', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_tickets_document_number'), ['document_number'], unique=True)

    op.create_table('vehicle_movements',
    sa.Column('document_number', sa.String(length=40), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approval_instance_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_movements_document_number'), ['document_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_movements_document_number'))

    op.drop_table('vehicle_movements')
    with op.batch_alter_table('trip_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_tickets_document_number'))

    op.drop_table('trip_tickets')
    with op.batch_alter_table('authority_to_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authority_to_drives_document_number'))

    op.drop_table('authority_to_drives')
    # ### end Alembic commands ###
