"""add last_pm_odometer and last_pm_date to vehicles for legacy vehicle registration baseline

Revision ID: f274c69d7b39
Revises: 7463625fac18
Create Date: 2026-07-18 17:15:41.878990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f274c69d7b39'
down_revision = '7463625fac18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pm_odometer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_pm_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('last_pm_date')
        batch_op.drop_column('last_pm_odometer')

    # ### end Alembic commands ###
