"""add fuel import batch tracking and fuel.delete permission

Revision ID: f425c85c573f
Revises: 3fdf2cde1ed4
Create Date: 2026-08-05 15:25:23.231332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f425c85c573f'
down_revision = '3fdf2cde1ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('imported_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fuel_transactions_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_foreign_key('fk_fuel_transactions_imported_by_users',
                                    'users', ['imported_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fuel_transactions_imported_by_users',
                                 type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fuel_transactions_import_batch_id'))
        batch_op.drop_column('imported_at')
        batch_op.drop_column('imported_by')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('import_filename')

    # ### end Alembic commands ###
